include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # avoid_print: false

analyzer:
  errors:
    invalid_annotation_target: ignore
    unintended_html_in_doc_comment: ignore
  plugins:
    - custom_lint
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
